#pragma once
#ifndef _MOD_PARA_H_
#define _MOD_PARA_H_

#define MOTION_TRESH 10
//#define GROUP_AREA_BUFFER_MAX 200000
#define GROUP_AREA_THRESH_MIN 100
#define GROUP_AREA_THRESH_MAX 100000
#define GROUP_NUM_THRESH 1000
#define CONTINUOUS_DETECTION_FRAMES 4
#define PRESERVATION_RATE 1.0f
#define WARNING_FRAMES 4

#endif // _MOD_PARA_H_